vich_uploader:
    db_driver: orm

    mappings:
       pin_image:
           uri_prefix: /uploads/pins/images
           upload_destination: '%kernel.project_dir%/public/uploads/pins/images'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
           
           inject_on_load: false
           delete_on_update: true
           delete_on_remove: true